dataset:
  root: "/mmlab_students/storageStudents/nguyenvd/Thanhld/WSI/dataset"
  
  order: "forward"

  brca:
    csv: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_brca/tcga_brca_subset.csv.zip"
    features: "${dataset.root}/TCGA-BRCA_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_brca"

  rcc:
    csv: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_rcc/tcga_kidney_subset.csv"
    features: "${dataset.root}/TCGA-RCC_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_rcc"

  nsclc:
    csv: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_nsclc/tcga_lung_subset.csv.zip"
    features: "${dataset.root}/TCGA-NSCLC_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_nsclc"

  esca:
    features: "${dataset.root}/TCGA-ESCA_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_esca"

  tgct:
    features: "${dataset.root}/TCGA-TGCT_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_tgct"

  cesc:
    features: "${dataset.root}/TCGA-CESC_processed/features/"
    splits: "${dataset.root}/wsi_dataset_annotation_cross_sites/tcga_cesc"

training:
  num_epochs: 10
  lr: 1.0e-5
  weight_decay: 1.0e-4
  seed: 0
  num_folds: 10
  num_tasks: 6

dataloader:
  batch_size: 1       
  num_workers: 0      

paths:
  task_prompts: "./task_prompts.pt"
  finetuned_checkpoints: "./checkpoints_ood/finetuned"
  merged_checkpoints: "./checkpoints_ood/merged"